worker-threads: 4
worker-fs-threads: 2
logger-level: info

testsuite-enabled: false

is-testing: false

server-port: 8080

dbconnection: 'postgresql://digest_sample_user:password@localhost:5432/digest_sample_db_1'
